### ISSUE TITLE
"The filename, directory name, or volume label syntax is incorrect."

### ISSUE THREAD

**Issue by woutershans** [tobiascornille/toledo-dl#1]
Thanks for the code and good documentation.
I followed all the steps, but get stuck with the following error message: "The filename, directory name, or volume label syntax is incorrect."
This happens at the point where youtube-dl is run. (line 39 in toledo-dl.py)

Any indication on what's wrong? Enclosed the cookies and input file according to your instructions.
[cookies.txt](https://github.com/tobiascornille/toledo-dl/files/7144263/cookies.txt)
[input.txt](https://github.com/tobiascornille/toledo-dl/files/7144264/input.txt)

**Comment by tobiascornille** [comment]
Hi! Sorry for the late answer. Could you try to clone the other branch [https://github.com/tobiascornille/toledo-dl/tree/jumpcutter-windows](https://github.com/tobiascornille/toledo-dl/tree/jumpcutter-windows) and run it again? It contains a newer version of the script. I will probably remove the old version if the other branch works for you.

Your cookies and input file look fine btw
