### ISSUE TITLE
Toledo serving another page for the script

### ISSUE THREAD

**Issue by ToxicMushroom** [tobiascornille/toledo-dl#3]
I've tried to use this script as described in the readme but the url `https://p.cygnus.cc.kuleuven.be/webapps/blackboard/content/listContent.jsp?course_id=%&content_id=%` (I replaced the ids with % here) sends me to 
![image](https://user-images.githubusercontent.com/32853531/156880317-9e8d9ad5-f41e-4191-b8b0-be84c36ca6f1.png)
 
I was able to get it working by first downloading the html pages manually from my browser and feeding them into the script instead of the request response but that's extra labour that I'd like to avoid

**Comment by ToxicMushroom** [comment]
Okay after further investigation it seems like the cookies.txt extension is breaking something.
When I added the raw cookie value in the headers param of request it doesn't go to this page and the script works fine

**Comment by tobiascornille** [comment]
Feel free to create a PR if you find the solution!

**Comment by ToxicMushroom** [comment]
I have some changes and improvements in my fork, namely 
- best quality downloads
- better regexes (in my experience).
- I cleaned up the readme instructions and switched to raw cookie copy method instead of an extension

I understand if switching from an extension to the developer menu is unwanted but I currently am not aware of good extensions to copy the site cookies for both firefox and chrome.
If you want I can do a draft PR until one such extension is found. Or we could switch to the dev-menu guide I appended to the readme currently and I just do a normal PR ?

**Comment by ToxicMushroom** [comment]
you can take a look at what I changed here: https://github.com/tobiascornille/toledo-dl/compare/main...ToxicMushroom:main

**Comment by tobiascornille** [comment]
@ToxicMushroom I actually had some problems with the extension, so I'd be happy to remove that dependency. However, does your technique also work on Chrome?

Feel free to open a PR already. I might just check if it's necessary to merge some of the changes in the [jumpcutter-windows](https://github.com/tobiascornille/toledo-dl/tree/jumpcutter-windows) branch, since it's newer.

**Comment by ToxicMushroom** [comment]
I've made a pr: https://github.com/tobiascornille/toledo-dl/pull/4 it does work on chrome :)
